---
title: "Analisis del nuevo proyecto"
author: "Leonardo A. Saravia"
date: "6/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

theme_set(theme_bw())

```

## Carga de datos


* Energy flux: The link between multitrophic biodiversity and ecosystem functioning, Barnes et al. 2018


```{r cargadedatos, echo=FALSE}

da <- read_csv("Data/energy_flux.csv") 

names(da)

ggplot( da, aes(abundance,biomass, color=species)) + geom_point() + scale_color_viridis_d()

ggsave( "Figures/AbundanciaVSBiomass.png")
```

# Ajuste por sitio

```{r ajustePowerLaw, echo=FALSE}

require(poweRlaw)

da <- da %>% mutate(bodysize = biomass / abundance )

da %>% count(sample)

da <- da %>% extract( sample,into= c("site","sampleNum"), "([[:alnum:]]+)-([[:alnum:]]+)")

da %>% count(site,sampleNum)

site1 <- da %>% filter(site=="3high")

pw1 <- conpl$new(site1$bodysize)
pw1$getXmin()
est <- estimate_pars(pw1)
pw1$setPars(est)
plot(pw1)
## Add in the fitted distribution
lines(pw1, col = 2)

ll <- da %>% group_by(site) %>% group_map( ~{pw1 <- conpl$new(.x$bodysize)
                                      pw1$getXmin()
                                      est <- estimate_pars(pw1)
                                      pw1$setPars(est)
                                      pw1
                                      dd <- plot(pw1)
                                      ll <- lines(pw1, col = 2)
                                      ggplot( dd, aes(x,y) ) + geom_point() + scale_x_log10() + scale_y_log10() + 
    geom_line(data=ll,aes(x,y, color="Power Law")) + ggtitle(.y)
})


```
